name: Allowlist Token

on:
  workflow_call:
    inputs:
      network:
        type: string
        required: true
      tokenAddress:
        type: string
        required: true
      tokenSymbol:
        type: string
        required: false

jobs:
  allowlist-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        run: npm install cac
      - name: Run allowlist script
        run: npx tsx ./src/lib/scripts/allowlist-token.ts --network ${{inputs.network}} --tokenAddress \"${{inputs.tokenAddress}}\" --tokenSymbol "${{inputs.tokenSymbol}}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Add ${{ inputs.tokenSymbol }} to ${{ inputs.network }} allowlist'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-allowlist-${{inputs.network}}-${{inputs.tokenAddress}}
          base: main
          delete-branch: true
          title: 'Allowlist ${{inputs.tokenSymbol}} on ${{inputs.network}}'
          body: |
            This PR was autogenerated by the allowlist Github action.
          draft: false
          labels: allowlist
